services:
  nats:
    image: nats:latest
    container_name: nephtys_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "--jetstream", "--store_dir", "/data", "-m", "8222" ]
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: nephtys_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: nephtys_renderer
    ports:
      - "8081:8081"

  grafana:
    image: grafana/grafana:latest
    container_name: nephtys_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    depends_on:
      - prometheus
      - renderer

volumes:
  nats-data:
