// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/nephtys/v1/streamer.proto

package streamer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest represents a single event sent by the client.
type IngestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of the event (maps to domain.StreamEvent.Type)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The raw JSON payload as bytes (maps to domain.StreamEvent.Payload)
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nephtys_v1_streamer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nephtys_v1_streamer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_nephtys_v1_streamer_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// IngestResponse is sent back when the stream is closed by the client,
// or if an error occurs and the server terminates the stream.
type IngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of events successfully processed.
	ProcessedCount int64 `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nephtys_v1_streamer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nephtys_v1_streamer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_nephtys_v1_streamer_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetProcessedCount() int64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

var File_proto_nephtys_v1_streamer_proto protoreflect.FileDescriptor

var file_proto_nephtys_v1_streamer_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x70, 0x68, 0x74, 0x79, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x70, 0x68, 0x74, 0x79, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a,
	0x0d, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x39, 0x0a, 0x0e,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x55, 0x0a, 0x08, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x6e, 0x65, 0x70, 0x68, 0x74, 0x79, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x6e, 0x65, 0x70, 0x68, 0x74, 0x79, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x20,
	0x5a, 0x1e, 0x6e, 0x65, 0x70, 0x68, 0x74, 0x79, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nephtys_v1_streamer_proto_rawDescOnce sync.Once
	file_proto_nephtys_v1_streamer_proto_rawDescData = file_proto_nephtys_v1_streamer_proto_rawDesc
)

func file_proto_nephtys_v1_streamer_proto_rawDescGZIP() []byte {
	file_proto_nephtys_v1_streamer_proto_rawDescOnce.Do(func() {
		file_proto_nephtys_v1_streamer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nephtys_v1_streamer_proto_rawDescData)
	})
	return file_proto_nephtys_v1_streamer_proto_rawDescData
}

var file_proto_nephtys_v1_streamer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nephtys_v1_streamer_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: nephtys.v1.IngestRequest
	(*IngestResponse)(nil), // 1: nephtys.v1.IngestResponse
}
var file_proto_nephtys_v1_streamer_proto_depIdxs = []int32{
	0, // 0: nephtys.v1.Streamer.StreamEvents:input_type -> nephtys.v1.IngestRequest
	1, // 1: nephtys.v1.Streamer.StreamEvents:output_type -> nephtys.v1.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_nephtys_v1_streamer_proto_init() }
func file_proto_nephtys_v1_streamer_proto_init() {
	if File_proto_nephtys_v1_streamer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nephtys_v1_streamer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IngestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nephtys_v1_streamer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nephtys_v1_streamer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nephtys_v1_streamer_proto_goTypes,
		DependencyIndexes: file_proto_nephtys_v1_streamer_proto_depIdxs,
		MessageInfos:      file_proto_nephtys_v1_streamer_proto_msgTypes,
	}.Build()
	File_proto_nephtys_v1_streamer_proto = out.File
	file_proto_nephtys_v1_streamer_proto_rawDesc = nil
	file_proto_nephtys_v1_streamer_proto_goTypes = nil
	file_proto_nephtys_v1_streamer_proto_depIdxs = nil
}
