// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/nephtys/v1/streamer.proto

package streamer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Streamer_StreamEvents_FullMethodName = "/nephtys.v1.Streamer/StreamEvents"
)

// StreamerClient is the client API for Streamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Streamer service allows external clients to push events into Nephtys in real-time.
type StreamerClient interface {
	// StreamEvents is a client-streaming RPC.
	// The client opens a stream and continuously sends IngestRequests.
	// The server processes these events with ultra-low latency.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestResponse], error)
}

type streamerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamerClient(cc grpc.ClientConnInterface) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[IngestRequest, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Streamer_ServiceDesc.Streams[0], Streamer_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Streamer_StreamEventsClient = grpc.ClientStreamingClient[IngestRequest, IngestResponse]

// StreamerServer is the server API for Streamer service.
// All implementations must embed UnimplementedStreamerServer
// for forward compatibility.
//
// Streamer service allows external clients to push events into Nephtys in real-time.
type StreamerServer interface {
	// StreamEvents is a client-streaming RPC.
	// The client opens a stream and continuously sends IngestRequests.
	// The server processes these events with ultra-low latency.
	StreamEvents(grpc.ClientStreamingServer[IngestRequest, IngestResponse]) error
	mustEmbedUnimplementedStreamerServer()
}

// UnimplementedStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamerServer struct{}

func (UnimplementedStreamerServer) StreamEvents(grpc.ClientStreamingServer[IngestRequest, IngestResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedStreamerServer) mustEmbedUnimplementedStreamerServer() {}
func (UnimplementedStreamerServer) testEmbeddedByValue()                  {}

// UnsafeStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamerServer will
// result in compilation errors.
type UnsafeStreamerServer interface {
	mustEmbedUnimplementedStreamerServer()
}

func RegisterStreamerServer(s grpc.ServiceRegistrar, srv StreamerServer) {
	// If the following call pancis, it indicates UnimplementedStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Streamer_ServiceDesc, srv)
}

func _Streamer_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamerServer).StreamEvents(&grpc.GenericServerStream[IngestRequest, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Streamer_StreamEventsServer = grpc.ClientStreamingServer[IngestRequest, IngestResponse]

// Streamer_ServiceDesc is the grpc.ServiceDesc for Streamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Streamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nephtys.v1.Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Streamer_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/nephtys/v1/streamer.proto",
}
